# Generated by Django 5.2.3 on 2025-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('research_agent', 'Research Agent'), ('formatting_agent', 'Formatting Agent'), ('delivery_agent', 'Delivery Agent')], default='research_agent', max_length=32),
        ),
    ]
