# Generated by Django 5.2.3 on 2025-06-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0002_agent_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence in findings (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to generated file', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('html', 'HTML'), ('markdown', 'Markdown'), ('docx', 'Word Document'), ('pdf', 'PDF')], default='html', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='key_insights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw structured data from agent'),
        ),
        migrations.AddField(
            model_name='report',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('competitive_intelligence', 'Competitive Intelligence Agent'), ('product_intelligence', 'Product Intelligence Agent'), ('market_trends', 'Market Trends Agent'), ('formatting_agent', 'Formatting Agent'), ('delivery_agent', 'Delivery Agent')], default='competitive_intelligence', max_length=32),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='research_agent.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(default='User', max_length=100)),
                ('query', models.TextField(help_text='The research query or topic')),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='Specific areas to focus on')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('delivery_format', models.CharField(choices=[('email', 'Email Only'), ('pdf', 'PDF Attachment'), ('docx', 'Word Document'), ('both', 'Email + Attachment')], default='email', max_length=20)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='research_agent.agent')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='research_agent.reportrequest'),
        ),
    ]
