# Generated by Django 5.2.3 on 2025-06-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0003_agent_is_active_report_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source URL for the report content'),
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(choices=[('competitive_intelligence_agent', 'Competitive Intelligence'), ('product_intelligence_agent', 'Product Intelligence'), ('market_trends_agent', 'Market Trends'), ('comprehensive_research', 'Comprehensive Multi-Agent Research')], default='comprehensive_research', max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('query_template', models.TextField(help_text='Template query for periodic reports')),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_date', models.DateTimeField()),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_format', models.CharField(default='email', max_length=20)),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('preferred_time', models.TimeField(default='09:00:00', help_text='Preferred delivery time')),
                ('total_reports_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['next_run_date', 'is_active'], name='research_ag_next_ru_5c0fed_idx'), models.Index(fields=['user_email'], name='research_ag_user_em_03d69f_idx')],
                'unique_together': {('user_email', 'agent_type', 'frequency')},
            },
        ),
    ]
