# Generated by Django 5.2.3 on 2025-07-22 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0004_report_source_url_reportsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='report',
            name='format',
        ),
        migrations.RemoveField(
            model_name='report',
            name='key_insights',
        ),
        migrations.RemoveField(
            model_name='report',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='word_count',
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_agent.agent'),
        ),
        migrations.AlterField(
            model_name='report',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
